### PR TITLE
Pass optional `postscriptName` parameter to fontkit

### PR DESCRIPTION
**Pull request by tsung-ju**
Currently passing .ttc files to `fromFile`, `fromBlob` or `fromUrl` causes an error, because fontkit returns a `Collection` instead of a `Font`. I added an optional `postscriptName` parameter which tells fontkit to return a specific font from the collection.

Here's an example usage:
```js
const metrics = await fromFile('NotoSans.ttc', 'NotoSans');
```

### CODE REVIEW

**Comment by michaeltaranto** [comment]
Thanks for looking at this. We have some work landing soon that introduces an options object as a second parameter to these APIs and that will clash with the approach of this PR currently.

Adding better support for type collections is definitely part of the plan, but want to consider this as a feature on top of the new work landing shortly if thats ok.

**Comment by paschun** [comment]
Would love to see this!

**Comment by michaeltaranto** [comment]
Sorry, returning to this now that we have completed both the unicode subset work and weight/variant support, and it looks like we didnt end up adding an options object.

I still prefer the extensibility of using an options object here, e.g.:
```ts
const metrics = await fromFile('<path>', {
  postscriptName: '...'
});
```

Have just been playing around with how we can improve the DX if users get this wrong, e.g. providing feedback when opening a collection without providing a `postscriptName` and was able to extract this which I think is helpful:

```
Error: Metrics cannot be unpacked for a font collection.

Either provide a single font file or specify a `postscriptName` in the options. For example:
------------------------------------------
const metrics = await fromFile('<path>', {
  postscriptName: 'AvenirNext-Bold'
});
------------------------------------------

Available `postscriptNames` in this collection are:
  - AvenirNext-Bold
  - AvenirNext-BoldItalic
  - AvenirNext-DemiBold
  - AvenirNext-DemiBoldItalic
  - AvenirNext-Italic
  - AvenirNext-Medium
  - AvenirNext-MediumItalic
  - AvenirNext-Regular
  - AvenirNext-Heavy
  - AvenirNext-HeavyItalic
  - AvenirNext-UltraLight
  - AvenirNext-UltraLightItalic
```

Are you happy for me to push to this PR?

**Comment by michaeltaranto** [comment]
Closing due to inactivity, but have opened #208 that goes a bit further as described [above]. Thanks for the push.

[above]: https://github.com/seek-oss/capsize/pull/156#issuecomment-2128323607

**Pull request closed without merging**
